/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.neefrankie.srv;

public class App {

    public static void main(String[] args) {
        System.out.println(Constants.WEB_ROOT);
        HttpServer server = new HttpServer();
        server.await();
    }
}
