/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.neefrankie.srv;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {

    public String getGreeting() {
        return "Hello World!";
    }

    @Test public void appHasAGreeting() {
        assertNotNull("app should have a greeting", getGreeting());
    }

    @Test public void parseUri() {
        String s = "GET /index.html HTTP/1.1";
        int index1 = s.indexOf(' ');
        System.out.println(index1);
        int index2 = s.indexOf(' ', index1 + 1);
        System.out.println(s.substring(index1+1, index2));
    }
}
